/**
 * Fixture host page for the documentation screenshots.
 *
 * The panel talks to exactly three Chrome APIs (`chrome.runtime.connect`,
 * `chrome.devtools.inspectedWindow.eval` and `.tabId`) and otherwise reaches
 * the inspected page through `window.__00__` plus a handful of CustomEvents
 * that `page-script.ts` answers. This file plays all of those roles at once
 * (background script, content script and page script) so `dist/panel.js` runs
 * unmodified against a frozen dataset.
 *
 * Everything here is invented demo data for a fictional team-chat app. Nothing
 * is read from a real deployment, so the screenshots can be regenerated by
 * anyone without a running backend.
 *
 * When the panel grows a tab or changes a message shape, update this file and
 * re-run `pnpm --filter @spooky-sync/devtools screenshots`.
 */
(function () {
  // A fixed clock keeps every regenerated screenshot byte-identical when
  // nothing changed: relative times ("3s ago") are rendered from these.
  const NOW = Date.UTC(2026, 8, 17, 9, 41, 0);
  const ago = (ms) => NOW - ms;
  Date.now = () => NOW;

  // ---------------------------------------------------------------------------
  // Query timings
  // ---------------------------------------------------------------------------

  // oxlint-disable-next-line unicorn/consistent-function-scoping -- keep every fixture helper inside the fixture
  const phase = (last, p50, p90, p99, count) => ({ lastMs: last, p50, p90, p99, count });

  const timings = (o) => ({
    ssp: phase(o.ssp[0], o.ssp[1], o.ssp[2], o.ssp[3], o.updates),
    sspStoreApply: phase(o.ssp[0] * 0.4, o.ssp[1] * 0.4, o.ssp[2] * 0.4, o.ssp[3] * 0.4, o.updates),
    sspCircuitStep: phase(
      o.ssp[0] * 0.45,
      o.ssp[1] * 0.45,
      o.ssp[2] * 0.45,
      o.ssp[3] * 0.45,
      o.updates
    ),
    sspTransform: phase(
      o.ssp[0] * 0.15,
      o.ssp[1] * 0.15,
      o.ssp[2] * 0.15,
      o.ssp[3] * 0.15,
      o.updates
    ),
    localFetch: phase(o.local[0], o.local[1], o.local[2], o.local[3], o.updates),
    remoteFetch: phase(o.remote[0], o.remote[1], o.remote[2], o.remote[3], o.updates),
    frontend: phase(o.frontend[0], o.frontend[1], o.frontend[2], o.frontend[3], o.updates),
    registration: { parseMs: o.reg[0], planMs: o.reg[1], snapshotMs: o.reg[2], wallMs: o.reg[3] },
    updateCount: o.updates,
    errorCount: o.errors ?? 0,
  });

  // ---------------------------------------------------------------------------
  // Active queries
  // ---------------------------------------------------------------------------

  const QUERIES = {
    814_233_901: {
      queryHash: 814233901,
      status: 'active',
      createdAt: ago(412_000),
      lastUpdate: ago(3_100),
      updateCount: 37,
      dataSize: 184_320,
      ttl: '10m',
      query:
        'SELECT * FROM message WHERE channel = $channel ORDER BY created_at DESC LIMIT 50 FETCH author',
      variables: { channel: 'channel:general' },
      listenerCount: 3,
      localCount: 50,
      remoteCount: 50,
      localIds: ['message:9f2c1a', 'message:7b04de', 'message:22aa90'],
      remoteIds: ['message:9f2c1a', 'message:7b04de', 'message:22aa90'],
      idsTruncated: true,
      timings: timings({
        ssp: [4.2, 3.8, 7.1, 19.4],
        local: [11.6, 9.9, 18.2, 41.0],
        remote: [0, 0, 0, 0],
        frontend: [1.4, 1.1, 2.6, 6.8],
        reg: [0.8, 2.1, 26.4, 31.7],
        updates: 37,
      }),
    },
    512_004_773: {
      queryHash: 512004773,
      status: 'updating',
      createdAt: ago(398_000),
      lastUpdate: ago(900),
      updateCount: 12,
      dataSize: 24_576,
      ttl: '10m',
      query: 'SELECT * FROM channel WHERE workspace = $workspace ORDER BY name',
      variables: { workspace: 'workspace:acme' },
      listenerCount: 1,
      localCount: 14,
      remoteCount: 14,
      timings: timings({
        ssp: [2.9, 2.4, 4.0, 9.2],
        local: [5.1, 4.6, 8.8, 12.4],
        remote: [0, 0, 0, 0],
        frontend: [0.9, 0.7, 1.5, 3.1],
        reg: [0.4, 1.2, 8.9, 10.9],
        updates: 12,
      }),
    },
    331_988_402: {
      queryHash: 331988402,
      status: 'active',
      createdAt: ago(401_000),
      lastUpdate: ago(64_000),
      updateCount: 4,
      dataSize: 3_072,
      ttl: '10m',
      query: 'SELECT * FROM user WHERE id = $auth.id',
      variables: {},
      listenerCount: 5,
      localCount: 1,
      remoteCount: 1,
      timings: timings({
        ssp: [1.1, 1.0, 1.6, 2.9],
        local: [2.2, 2.0, 3.1, 4.4],
        remote: [0, 0, 0, 0],
        frontend: [0.5, 0.4, 0.8, 1.2],
        reg: [0.3, 0.9, 4.1, 5.3],
        updates: 4,
      }),
    },
    907_461_255: {
      queryHash: 907461255,
      status: 'active',
      createdAt: ago(122_000),
      lastUpdate: ago(11_400),
      updateCount: 9,
      dataSize: 40_960,
      ttl: '10m',
      query: 'SELECT * FROM task WHERE assigned_to = $auth.id AND done = false ORDER BY due_at',
      variables: {},
      listenerCount: 2,
      localCount: 23,
      remoteCount: 23,
      timings: timings({
        ssp: [9.8, 8.1, 21.6, 58.3],
        local: [31.4, 27.7, 62.9, 118.5],
        remote: [24.8, 21.2, 44.6, 96.1],
        frontend: [3.2, 2.8, 5.9, 11.0],
        reg: [1.1, 3.4, 44.2, 49.7],
        updates: 9,
        errors: 1,
      }),
    },
    140_772_318: {
      queryHash: 140772318,
      status: 'active',
      createdAt: ago(96_000),
      lastUpdate: ago(29_000),
      updateCount: 6,
      dataSize: 1_024,
      ttl: '5m',
      query: 'SELECT count() FROM message WHERE channel = $channel GROUP ALL',
      variables: { channel: 'channel:general' },
      listenerCount: 1,
      localCount: 1,
      remoteCount: 1,
      timings: timings({
        ssp: [1.9, 1.7, 2.8, 5.0],
        local: [3.3, 3.0, 4.9, 7.2],
        remote: [12.7, 11.4, 19.8, 33.5],
        frontend: [0.6, 0.5, 0.9, 1.4],
        reg: [0.3, 1.0, 6.2, 7.5],
        updates: 6,
      }),
    },
    205_913_664: {
      queryHash: 205913664,
      status: 'initializing',
      createdAt: ago(1_800),
      lastUpdate: ago(1_800),
      updateCount: 0,
      dataSize: 0,
      ttl: '10m',
      query: 'SELECT * FROM membership WHERE channel = $channel FETCH user',
      variables: { channel: 'channel:design' },
      listenerCount: 1,
      localCount: 0,
      remoteCount: 0,
    },
  };

  /** Rows are pulled on demand by the Data tab, never pushed with the state. */
  const QUERY_ROWS = {
    814233901: {
      data: [
        {
          id: 'message:9f2c1a',
          channel: 'channel:general',
          author: { id: 'user:mira', name: 'Mira Oyelaran' },
          body: 'Shipping the migration behind the flag tonight.',
          created_at: '2026-09-17T09:40:56.812Z',
        },
        {
          id: 'message:7b04de',
          channel: 'channel:general',
          author: { id: 'user:tomas', name: 'Tomas Berg' },
          body: 'Replica caught up, drift is back to zero.',
          created_at: '2026-09-17T09:38:11.004Z',
        },
      ],
      localArray: ['message:9f2c1a', 'message:7b04de', 'message:22aa90'],
      remoteArray: ['message:9f2c1a', 'message:7b04de', 'message:22aa90'],
    },
  };

  // ---------------------------------------------------------------------------
  // Events
  // ---------------------------------------------------------------------------

  // Event names and payload shapes mirror what `DevToolsService` actually
  // records (`QUERY_UPDATED`, `STREAM_UPDATE`, `MUTATION_REQUEST_EXECUTION`,
  // `LOCAL_QUERY`, `QUERY_STATUS_CHANGED`, `QUERY_REQUEST_INIT`).
  const EVENTS = [
    {
      eventType: 'QUERY_UPDATED',
      at: 3_100,
      payload: { queryHash: 814233901, recordCount: 50 },
    },
    {
      eventType: 'STREAM_UPDATE',
      at: 3_140,
      payload: {
        queryHash: 814233901,
        op: 'insert',
        localCount: 50,
        materializationTimeMs: 4.2,
        storeApplyMs: 1.7,
        circuitStepMs: 1.9,
        transformMs: 0.6,
      },
    },
    {
      eventType: 'MUTATION_REQUEST_EXECUTION',
      at: 12_600,
      payload: {
        mutation: { type: 'update', fields: ['done', 'updated_at'], selector: 'task:44cd1' },
      },
    },
    {
      eventType: 'LOCAL_QUERY',
      at: 12_640,
      payload: {
        query: 'SELECT * FROM task WHERE assigned_to = $auth LIMIT 50',
        duration: 31.4,
        success: true,
      },
    },
    {
      eventType: 'QUERY_STATUS_CHANGED',
      at: 1_700,
      payload: { queryHash: 205913664, status: 'initializing' },
    },
    {
      eventType: 'QUERY_REQUEST_INIT',
      at: 1_800,
      payload: {
        queryHash: 205913664,
        query: 'SELECT * FROM membership WHERE channel = $channel FETCH user',
        variables: {},
      },
    },
  ].map((e, i) => ({
    id: i + 1,
    timestamp: ago(e.at),
    eventType: e.eventType,
    payload: e.payload,
  }));

  // ---------------------------------------------------------------------------
  // Stack / versions
  // ---------------------------------------------------------------------------

  const heartbeatSamples = () => {
    const out = [];
    for (let i = 29; i >= 0; i--) {
      const jitter = [58, 61, 64, 57, 72, 63, 59, 66, 61, 55][i % 10];
      out.push({ ts: ago(i * 15_000), ms: i === 11 ? null : jitter + (i % 3) * 4, ok: i !== 11 });
    }
    return out;
  };

  const VERSIONS = {
    frontend: { core: '0.0.1-canary.265', wasm: '0.0.1-canary.265', surrealdb: '3.1.5' },
    backend: { ssp: '0.0.1-canary.265', scheduler: '0.0.1-canary.265', surrealdb: '3.1.5' },
    entities: [
      {
        entity: 'scheduler',
        id: 'scheduler-0',
        ip: '10.0.3.11',
        status: 'ready',
        version: '0.0.1-canary.265',
        surrealdb_version: '3.1.5',
        uptime_seconds: 149_820,
        heartbeat: {
          enabled: true,
          stale: false,
          last_e2e_ms: 61,
          last_ok_epoch_ms: ago(9_000),
          consecutive_failures: 0,
          interval_secs: 15,
          samples: heartbeatSamples(),
        },
      },
      {
        entity: 'ssp',
        id: 'ssp-0',
        ip: '10.0.3.21',
        status: 'ready',
        version: '0.0.1-canary.265',
        views: 38,
        uptime_seconds: 149_640,
      },
      {
        entity: 'ssp',
        id: 'ssp-1',
        ip: '10.0.3.22',
        status: 'ready',
        version: '0.0.1-canary.265',
        views: 34,
        uptime_seconds: 86_400,
      },
      {
        entity: 'backend',
        id: 'api',
        ip: '10.0.3.31',
        status: 'healthy',
        version: '0.0.1-canary.265',
        uptime_seconds: 149_400,
      },
    ],
  };

  // ---------------------------------------------------------------------------
  // Database
  // ---------------------------------------------------------------------------

  const APP_TABLES = ['channel', 'membership', 'message', 'task', 'user', 'workspace'];
  const INTERNAL_TABLES = ['_00_list_ref', '_00_query', '_00_version'];
  const ALL_TABLES = [...APP_TABLES, ...INTERNAL_TABLES].toSorted();

  const TABLE_ROWS = {
    message: [
      {
        id: 'message:9f2c1a',
        channel: 'channel:general',
        author: 'user:mira',
        body: 'Shipping the migration behind the flag tonight.',
        pinned: false,
        created_at: '2026-09-17T09:40:56.812Z',
      },
      {
        id: 'message:7b04de',
        channel: 'channel:general',
        author: 'user:tomas',
        body: 'Replica caught up, drift is back to zero.',
        pinned: false,
        created_at: '2026-09-17T09:38:11.004Z',
      },
      {
        id: 'message:22aa90',
        channel: 'channel:general',
        author: 'user:iris',
        body: 'Can someone look at the failing e2e gate?',
        pinned: true,
        created_at: '2026-09-17T09:31:47.551Z',
      },
      {
        id: 'message:5c18b3',
        channel: 'channel:design',
        author: 'user:mira',
        body: 'New bento tiles are on staging.',
        pinned: false,
        created_at: '2026-09-17T09:12:03.220Z',
      },
      {
        id: 'message:e04771',
        channel: 'channel:design',
        author: 'user:nadia',
        body: 'Palette reads better at 14px.',
        pinned: false,
        created_at: '2026-09-17T08:58:39.907Z',
      },
      {
        id: 'message:1ab5cf',
        channel: 'channel:random',
        author: 'user:tomas',
        body: 'Coffee machine is down again.',
        pinned: false,
        created_at: '2026-09-17T08:41:12.118Z',
      },
      {
        id: 'message:88de20',
        channel: 'channel:general',
        author: 'user:iris',
        body: 'Backfill finished, 738k rows.',
        pinned: false,
        created_at: '2026-09-17T08:22:55.640Z',
      },
      {
        id: 'message:3f90ac',
        channel: 'channel:general',
        author: 'user:mira',
        body: 'Rolling the scheduler to canary.265.',
        pinned: false,
        created_at: '2026-09-17T07:59:30.081Z',
      },
      {
        id: 'message:cc7412',
        channel: 'channel:design',
        author: 'user:nadia',
        body: 'Wordmark only in the header, no tagline.',
        pinned: false,
        created_at: '2026-09-17T07:44:18.302Z',
      },
      {
        id: 'message:6b2205',
        channel: 'channel:random',
        author: 'user:iris',
        body: 'Standup moved to 10:15.',
        pinned: false,
        created_at: '2026-09-17T07:30:02.775Z',
      },
    ],
    channel: [
      {
        id: 'channel:general',
        workspace: 'workspace:acme',
        name: 'general',
        topic: 'Everything that matters',
        private: false,
      },
      {
        id: 'channel:design',
        workspace: 'workspace:acme',
        name: 'design',
        topic: 'Pixels and palettes',
        private: false,
      },
      {
        id: 'channel:random',
        workspace: 'workspace:acme',
        name: 'random',
        topic: null,
        private: false,
      },
    ],
    user: [
      { id: 'user:mira', name: 'Mira Oyelaran', email: 'mira@acme.test', is_admin: true },
      { id: 'user:tomas', name: 'Tomas Berg', email: 'tomas@acme.test', is_admin: false },
      { id: 'user:iris', name: 'Iris Fontaine', email: 'iris@acme.test', is_admin: false },
      { id: 'user:nadia', name: 'Nadia Haddad', email: 'nadia@acme.test', is_admin: false },
    ],
  };

  const TABLE_TOTALS = {
    message: 14_208,
    channel: 14,
    user: 96,
    task: 231,
    membership: 412,
    workspace: 3,
  };

  // ---------------------------------------------------------------------------
  // Storage
  // ---------------------------------------------------------------------------

  const STORAGE_INFO = {
    at: NOW,
    engine: { kind: 'sqlite', store: 'OPFS SAHPool', bucketId: 'acme-chat' },
    health: { status: 'persistent', fallback: false, role: 'leader' },
    tabs: {
      active: true,
      role: 'leader',
      tabId: 'tab-7f21c4',
      leadershipId: 3,
      leaderTabId: 'tab-7f21c4',
      followers: 2,
      relayedBatches: 148,
    },
    browser: {
      persisted: true,
      usage: 78_643_200,
      quota: 1_073_741_824,
      usageDetails: { fileSystem: 74_448_896, indexedDB: 4_194_304 },
    },
    opfs: {
      supported: true,
      entries: [
        { path: '/acme-chat/sp00ky.sqlite3', kind: 'file', size: 62_914_560 },
        { path: '/acme-chat/sp00ky.sqlite3-wal', kind: 'file', size: 8_388_608 },
        { path: '/acme-chat/blobs', kind: 'directory' },
        { path: '/acme-chat/blobs/avatar-mira.webp', kind: 'file', size: 21_504 },
        { path: '/acme-chat/blobs/avatar-tomas.webp', kind: 'file', size: 19_968 },
      ],
      totalBytes: 71_344_640,
      truncated: false,
    },
    blobs: {
      entries: 42,
      totalBytes: 5_242_880,
      budgetBytes: 52_428_800,
      pinnedBytes: 1_048_576,
      evictedEntries: 2,
      evictedBytes: 262_144,
      reconciledEntries: 40,
      hits: 391,
      misses: 44,
      persistent: true,
      persistPaused: false,
    },
    sqliteStats: {
      roundTrips: 1_284,
      proxiedOps: 96,
      byType: { select: 941, exec: 288, batch: 55 },
      queueWaitMs: 0.7,
      workerMs: 18.9,
      rpcOverheadMs: 1.2,
      parseMs: 3.4,
      rowsParsed: 48_207,
      bytesParsed: 9_437_184,
      relationFetches: 612,
      batchStatements: 55,
      maxBatch: 400,
      inFlight: 0,
      maxInFlight: 3,
    },
    engineDiagnostics: {
      engine: 'sqlite',
      bucketId: 'acme-chat',
      useOpfs: true,
      workerSelectConfigured: true,
      workerSelectEffective: true,
      dbSizeBytes: 62_914_560,
      freelistBytes: 1_048_576,
      tableCounts: [
        { table: 'message', rows: 14_208 },
        { table: 'membership', rows: 412 },
        { table: 'task', rows: 231 },
        { table: 'user', rows: 96 },
        { table: 'channel', rows: 14 },
        { table: '_00_query', rows: 6 },
      ],
    },
  };

  // ---------------------------------------------------------------------------
  // Access: flags + impersonation
  // ---------------------------------------------------------------------------

  const FLAGS_SNAPSHOT = {
    at: NOW,
    userId: 'user:mira',
    isAdmin: true,
    flags: [
      {
        key: 'threaded-replies',
        description: 'Reply threads under a message instead of inline quoting.',
        variants: ['on', 'off'],
        default_variant: 'off',
        enabled: true,
        rules: [
          { kind: 'allowlist', variant: 'on', users: ['user:mira', 'user:nadia'], priority: 10 },
          { kind: 'rollout', variant: 'on', percent: 25, priority: 20 },
        ],
        updated_at: '2026-09-16T18:04:11.000Z',
        selfAllowlistedVariant: 'on',
      },
      {
        key: 'sqlite-local-engine',
        description: 'Use the SQLite local cache instead of SurrealDB WASM.',
        variants: ['sqlite', 'surreal'],
        default_variant: 'surreal',
        enabled: true,
        rules: [{ kind: 'rollout', variant: 'sqlite', percent: 50, priority: 10 }],
        updated_at: '2026-09-14T11:22:03.000Z',
      },
      {
        key: 'message-reactions',
        description: 'Emoji reactions on messages.',
        variants: ['on', 'off'],
        default_variant: 'off',
        enabled: false,
        rules: [],
        updated_at: '2026-09-02T08:15:40.000Z',
      },
    ],
    assignments: [
      { key: 'threaded-replies', variant: 'on' },
      { key: 'sqlite-local-engine', variant: 'sqlite' },
      { key: 'message-reactions', variant: 'off' },
    ],
    overrides: { 'sqlite-local-engine': { variant: 'surreal' } },
  };

  const IMPERSONATION_USERS = [
    { id: 'user:tomas', name: 'Tomas Berg', email: 'tomas@acme.test', is_admin: false },
    { id: 'user:iris', name: 'Iris Fontaine', email: 'iris@acme.test', is_admin: false },
    { id: 'user:nadia', name: 'Nadia Haddad', email: 'nadia@acme.test', is_admin: false },
    { id: 'user:mira', name: 'Mira Oyelaran', email: 'mira@acme.test', is_admin: true },
  ];

  const IMPERSONATION_STATUS = {
    enabled: true,
    isAdmin: true,
    current: null,
    active: [],
  };

  // ---------------------------------------------------------------------------
  // The state the panel receives
  // ---------------------------------------------------------------------------

  const STATE = {
    eventsHistory: EVENTS,
    activeQueries: QUERIES,
    auth: { authenticated: true, userId: 'user:mira', timestamp: ago(402_000) },
    version: '0.0.1-canary.265',
    versions: VERSIONS,
    database: {
      tables: ALL_TABLES,
      engine: 'sqlite',
      tableData: {},
      storage: { status: 'persistent', fallback: false, role: 'leader' },
      tabs: STORAGE_INFO.tabs,
    },
  };

  // ---------------------------------------------------------------------------
  // SurrealQL responder: only the statements the panel itself issues.
  // ---------------------------------------------------------------------------

  function answerQuery(query) {
    const sql = String(query).trim();

    if (sql === 'INFO FOR DB') {
      const tables = {};
      for (const t of ALL_TABLES) tables[t] = `DEFINE TABLE ${t} SCHEMAFULL`;
      return [{ status: 'OK', result: { tables } }];
    }

    const count = sql.match(/^SELECT count\(\) FROM (\S+) GROUP ALL$/i);
    if (count) {
      return [
        {
          status: 'OK',
          result: [{ count: TABLE_TOTALS[count[1]] ?? TABLE_ROWS[count[1]]?.length ?? 0 }],
        },
      ];
    }

    const select = sql.match(/^SELECT \* FROM (\S+) LIMIT (\d+) START (\d+)$/i);
    if (select) {
      const rows = TABLE_ROWS[select[1]] ?? [];
      const start = Number(select[3]);
      return [{ status: 'OK', result: rows.slice(start, start + Number(select[2])) }];
    }

    return [{ status: 'OK', result: [] }];
  }

  // ---------------------------------------------------------------------------
  // The inspected page (`window.__00__`)
  // ---------------------------------------------------------------------------

  window.__00__ = {
    version: STATE.version,
    getState: () => STATE,
    getQueryRows: async (hash) => QUERY_ROWS[hash] ?? null,
    getTableData: async (table) => TABLE_ROWS[table] ?? [],
    updateTableRow: async () => ({ success: true }),
    deleteTableRow: async () => ({ success: true }),
    refreshVersions: async () => VERSIONS,
    clearHistory: () => {
      STATE.eventsHistory = [];
    },
  };

  // The page-script half: every async op is dispatched into the page as a
  // CustomEvent and answered by posting a correlated message back.
  // oxlint-disable-next-line unicorn/consistent-function-scoping -- keep every fixture helper inside the fixture
  const reply = (payload) =>
    window.postMessage({ source: 'sp00ky-devtools-page', ...payload }, '*');

  window.addEventListener('SP00KY_RUN_QUERY', (e) => {
    const { requestId, query } = e.detail;
    reply({ type: 'SP00KY_QUERY_RESPONSE', requestId, success: true, data: answerQuery(query) });
  });

  window.addEventListener('SP00KY_STORAGE_OP', (e) => {
    const { requestId, op } = e.detail;
    reply({
      type: 'SP00KY_STORAGE_INFO_RESPONSE',
      requestId,
      success: true,
      data: op === 'persist' ? { persisted: true } : STORAGE_INFO,
    });
  });

  window.addEventListener('SP00KY_FLAG_OP', (e) => {
    const { requestId, op } = e.detail;
    reply({
      type: 'SP00KY_FLAG_RESPONSE',
      requestId,
      success: true,
      data: op === 'list' ? FLAGS_SNAPSHOT : { success: true },
    });
  });

  window.addEventListener('SP00KY_IMPERSONATE_OP', (e) => {
    const { requestId, op, args } = e.detail;
    let data = { success: true, ...IMPERSONATION_STATUS };
    if (op === 'listUsers') {
      const term = String(args?.search ?? '').toLowerCase();
      data = {
        success: true,
        users: IMPERSONATION_USERS.filter(
          (u) => !term || u.id.includes(term) || u.name.toLowerCase().includes(term)
        ),
      };
    }
    reply({ type: 'SP00KY_IMPERSONATE_RESPONSE', requestId, success: true, data });
  });

  // ---------------------------------------------------------------------------
  // The Chrome APIs the panel uses
  // ---------------------------------------------------------------------------

  const listeners = [];
  /** Deliver a message to the panel the way the background script would. */
  const push = (message) => listeners.forEach((l) => l({ frameId: 0, ...message }));

  // The content-script relay: page messages become port messages.
  window.addEventListener('message', (e) => {
    if (e.source !== window || e.data?.source !== 'sp00ky-devtools-page') return;
    push(e.data);
  });

  const port = {
    name: 'sp00ky-devtools',
    postMessage(message) {
      if (message?.type === 'GET_SP00KY_STATE') {
        push({ type: 'SP00KY_STATE_CHANGED', state: STATE });
      }
    },
    disconnect() {},
    onMessage: { addListener: (l) => listeners.push(l), removeListener: () => {} },
    onDisconnect: { addListener: () => {}, removeListener: () => {} },
  };

  window.chrome = {
    runtime: {
      connect() {
        // Announce the client and its state the way background.js does once the
        // panel's port is up.
        setTimeout(() => {
          push({
            type: 'SP00KY_FRAMES',
            frames: [{ frameId: 0, url: 'https://chat.acme.test/', version: STATE.version }],
          });
          push({ type: 'SP00KY_DETECTED', data: { state: STATE } });
          push({ type: 'MCP_STATUS', enabled: true, connected: true, port: 9315 });
        }, 0);
        return port;
      },
    },
    devtools: {
      inspectedWindow: {
        tabId: 1,
        /** Chrome resolves a returned promise before invoking the callback. */
        eval(code, optionsOrCallback, maybeCallback) {
          const cb = typeof optionsOrCallback === 'function' ? optionsOrCallback : maybeCallback;
          void (async () => {
            try {
              // oxlint-disable-next-line no-eval -- this stub exists to be the page's eval
              const result = await (0, eval)(code);
              cb?.(result, null);
            } catch (error) {
              cb?.(undefined, { value: String(error) });
            }
          })();
        },
      },
    },
  };
})();
