//! Query allowlist: the SSP refuses to register a view whose SHAPE is not one
//! the application ships.
//!
//! `fn::query::register` forwards `$config.surql` as an opaque string, the
//! scheduler forwards the body verbatim, and until here the SSP only checked
//! that the text parses, that every scanned table carries a PERMISSIONS clause
//! and that no opaque field is evaluated. Nothing pinned the shape of a query
//! to what the app actually asks for, so any token holder could register an
//! expensive join, probe non-projected columns, or hold arbitrary views open.
//!
//! # Shape, not text
//!
//! The allowlist is generated by RUNNING the app's query module against a
//! recording client (`@spooky-sync/query-allowlist`), so what it holds is the
//! builder's output for placeholder inputs: `LIMIT 1 START 1`, `id = $id`,
//! `_or`-branch names like `white__or0`. A live registration differs in every
//! one of those without differing in what it computes. The comparison is
//! therefore over a [`Shape`] derived from the converter's `OperatorPlan`, with
//! everything a caller can vary at runtime masked:
//!
//! - LIMIT / START numbers (windowed lists page; `.one()` is `LIMIT 1`).
//! - `$param` names and literal values. The builder binds every WHERE value
//!   as a `$param` and inlines related-subquery values as literals; neither
//!   identifies the shape.
//! - The NUMBER of OR branches: `(db = $a OR db = $b OR db = $c)` and
//!   `(db = $a)` are one shape, because `And`/`Or` children are a set.
//! - Projection column order.
//!
//! Everything else is exact: the table, the projected columns, every related
//! subquery (alias, parent key and its own shape), ORDER BY fields and
//! directions, and for a static entry the WHERE field/operator set.
//!
//! # `whereMode: any`
//!
//! A builder whose `where` comes from a caller argument (`qGamesWindow(db,
//! where, ...)`) has no enumerable WHERE. The generator marks it `any` and the
//! SSP matches it on the SKELETON (the shape with the root WHERE removed),
//! then admits the actual predicate only if it is builder grammar: `field op
//! $param` leaves joined by AND/OR, every field a column of the scanned table.
//! That keeps the probing surface at "what the builder can express over the
//! table's own columns", which permissions already bound row-wise.
//!
//! # One normaliser
//!
//! The generator emits raw surql and never hashes. Both the allowlist entries
//! and the incoming registration go through the converter and this module, so
//! there is exactly one definition of "same shape" and it lives here. Every
//! `match` is exhaustive with no wildcard arm: a new plan or predicate variant
//! is a compile error, not a silent hole (same discipline as `merge_key.rs`).

use crate::converter::{convert_surql_to_dbsp_with_links, LinkMap};
use crate::operator::plan::{OperatorPlan, Projection};
use crate::operator::predicate::Predicate;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use ssp_protocol::snapshot_hash::canonical_json;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt;
use std::str::FromStr;

/// Enforcement mode. `SPKY_SSP_QUERY_ALLOWLIST` / `sync.queryAllowlist`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Mode {
    /// Never consulted. Today's behaviour.
    #[default]
    Off,
    /// Decide and count, log a miss, admit anyway. The discovery loop for a
    /// tenant switching on: every logged miss is a shape the generator did not
    /// see.
    Warn,
    /// Refuse a miss with HTTP 403 `not_allowlisted`.
    Enforce,
}

impl FromStr for Mode {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_ascii_lowercase().as_str() {
            "" | "off" | "false" | "0" => Ok(Mode::Off),
            "warn" => Ok(Mode::Warn),
            "enforce" | "true" | "1" => Ok(Mode::Enforce),
            other => Err(format!(
                "invalid query allowlist mode '{other}' (expected off | warn | enforce)"
            )),
        }
    }
}

impl fmt::Display for Mode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Mode::Off => "off",
            Mode::Warn => "warn",
            Mode::Enforce => "enforce",
        })
    }
}

/// How an entry's root WHERE is matched.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum WhereMode {
    /// The recorded WHERE (field/operator set) is part of the shape.
    Static,
    /// The root WHERE is caller-supplied: match the skeleton, validate the
    /// predicate against builder grammar.
    Any,
}

/// One allowlisted query, as written by the generator into
/// `_00_query_allowlist.entries[]`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Entry {
    pub name: String,
    pub surql: String,
    #[serde(rename = "whereMode", default = "WhereMode::static_default")]
    pub where_mode: WhereMode,
    /// Provenance, for the refusal reason and `/info`.
    #[serde(default)]
    pub app: String,
    #[serde(default)]
    pub version: String,
}

impl WhereMode {
    fn static_default() -> Self {
        WhereMode::Static
    }
}

/// Comparison operator of a builder leaf.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Op {
    Eq,
    Neq,
    Gt,
    Gte,
    Lt,
    Lte,
}

/// The right-hand side of a comparison, masked.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Rhs {
    /// Any registration param (`$id`, `$white__or3`, `$auth.id`).
    Param,
    /// A subquery correlation ref (`{"$param": "parent.id"}`). Structural: it
    /// is how the converter expresses the parent key, so it stays verbatim.
    Parent(String),
    /// A baked literal (related-subquery values, `WHERE published = true`).
    Lit,
}

/// A predicate with params, literals and branch counts masked.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(tag = "t", rename_all = "lowercase")]
pub enum Pred {
    True,
    False,
    Cmp {
        field: String,
        op: Op,
        rhs: Rhs,
    },
    Prefix {
        field: String,
    },
    /// `$param OP value`: row-independent gate, only its operator matters.
    ParamCmp {
        op: Op,
    },
    And {
        of: BTreeSet<Pred>,
    },
    Or {
        of: BTreeSet<Pred>,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum JoinKind {
    Inner,
    Semi,
    Anti,
}

/// A plan with everything a caller can vary at runtime masked. See the module
/// docs for the exact list.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(tag = "op", rename_all = "lowercase")]
pub enum Shape {
    Scan {
        table: String,
    },
    Filter {
        input: Box<Shape>,
        predicate: Pred,
    },
    Join {
        kind: JoinKind,
        left: Box<Shape>,
        right: Box<Shape>,
        on: (String, String),
    },
    Union {
        left: Box<Shape>,
        right: Box<Shape>,
    },
    Distinct {
        input: Box<Shape>,
    },
    Project {
        input: Box<Shape>,
        all: bool,
        /// `(field, alias)`, order-insensitive.
        fields: BTreeSet<(String, Option<String>)>,
        /// alias → (parent key, shape). Alias-keyed so subquery order never
        /// matters.
        subqueries: BTreeMap<String, (Option<(String, String)>, Box<Shape>)>,
    },
    Limit {
        input: Box<Shape>,
        /// `(field, direction)` exact and ordered. The numbers are gone: the
        /// converter only emits this node when a LIMIT is present, and a
        /// window's `LIMIT n START m` are exactly what a caller pages with.
        order_by: Vec<(String, String)>,
    },
}

fn mask_rhs(value: &Value) -> Rhs {
    match value
        .as_object()
        .and_then(|o| o.get("$param"))
        .and_then(Value::as_str)
    {
        Some(p) if p.starts_with("parent.") => Rhs::Parent(p.to_string()),
        Some(_) => Rhs::Param,
        None => Rhs::Lit,
    }
}

fn mask_predicate(pred: &Predicate) -> Pred {
    let cmp = |field: &crate::types::Path, op: Op, value: &Value| Pred::Cmp {
        field: field.as_str(),
        op,
        rhs: mask_rhs(value),
    };
    match pred {
        Predicate::True => Pred::True,
        Predicate::False => Pred::False,
        Predicate::Eq { field, value } => cmp(field, Op::Eq, value),
        Predicate::Neq { field, value } => cmp(field, Op::Neq, value),
        Predicate::Gt { field, value } => cmp(field, Op::Gt, value),
        Predicate::Gte { field, value } => cmp(field, Op::Gte, value),
        Predicate::Lt { field, value } => cmp(field, Op::Lt, value),
        Predicate::Lte { field, value } => cmp(field, Op::Lte, value),
        Predicate::Prefix { field, .. } => Pred::Prefix {
            field: field.as_str(),
        },
        Predicate::ParamEq { .. } => Pred::ParamCmp { op: Op::Eq },
        Predicate::ParamNeq { .. } => Pred::ParamCmp { op: Op::Neq },
        Predicate::ParamGt { .. } => Pred::ParamCmp { op: Op::Gt },
        Predicate::ParamGte { .. } => Pred::ParamCmp { op: Op::Gte },
        Predicate::ParamLt { .. } => Pred::ParamCmp { op: Op::Lt },
        Predicate::ParamLte { .. } => Pred::ParamCmp { op: Op::Lte },
        Predicate::And { predicates } => collapse(Pred::And {
            of: predicates.iter().map(mask_predicate).collect(),
        }),
        Predicate::Or { predicates } => collapse(Pred::Or {
            of: predicates.iter().map(mask_predicate).collect(),
        }),
    }
}

/// An AND/OR that masked down to one child IS that child: `(white = $a OR
/// white = $b)` and `white = $a` are the same shape, and the converter only
/// wraps a node when there are two or more branches.
fn collapse(pred: Pred) -> Pred {
    match pred {
        Pred::And { of } | Pred::Or { of } if of.len() == 1 => {
            of.into_iter().next().expect("one child")
        }
        other => other,
    }
}

impl Shape {
    pub fn of(plan: &OperatorPlan) -> Shape {
        match plan {
            OperatorPlan::Scan { table } => Shape::Scan {
                table: table.clone(),
            },
            OperatorPlan::Filter { input, predicate } => Shape::Filter {
                input: Box::new(Shape::of(input)),
                predicate: mask_predicate(predicate),
            },
            OperatorPlan::Join { left, right, on } => Shape::Join {
                kind: JoinKind::Inner,
                left: Box::new(Shape::of(left)),
                right: Box::new(Shape::of(right)),
                on: (on.left_field.as_str(), on.right_field.as_str()),
            },
            OperatorPlan::SemiJoin { left, right, on } => Shape::Join {
                kind: JoinKind::Semi,
                left: Box::new(Shape::of(left)),
                right: Box::new(Shape::of(right)),
                on: (on.left_field.as_str(), on.right_field.as_str()),
            },
            OperatorPlan::AntiJoin { left, right, on } => Shape::Join {
                kind: JoinKind::Anti,
                left: Box::new(Shape::of(left)),
                right: Box::new(Shape::of(right)),
                on: (on.left_field.as_str(), on.right_field.as_str()),
            },
            OperatorPlan::Union { left, right } => Shape::Union {
                left: Box::new(Shape::of(left)),
                right: Box::new(Shape::of(right)),
            },
            OperatorPlan::Distinct { input } => Shape::Distinct {
                input: Box::new(Shape::of(input)),
            },
            OperatorPlan::Project { input, projections } => {
                let mut all = false;
                let mut fields = BTreeSet::new();
                let mut subqueries = BTreeMap::new();
                for proj in projections {
                    match proj {
                        Projection::All => all = true,
                        Projection::Field { field, alias } => {
                            fields.insert((field.as_str(), alias.clone()));
                        }
                        Projection::Subquery {
                            alias,
                            plan,
                            parent_key,
                        } => {
                            subqueries.insert(
                                alias.clone(),
                                (
                                    parent_key
                                        .as_ref()
                                        .map(|k| (k.child_field.clone(), k.parent_field.clone())),
                                    Box::new(Shape::of(plan)),
                                ),
                            );
                        }
                    }
                }
                Shape::Project {
                    input: Box::new(Shape::of(input)),
                    all,
                    fields,
                    subqueries,
                }
            }
            OperatorPlan::Limit {
                input, order_by, ..
            } => Shape::Limit {
                input: Box::new(Shape::of(input)),
                order_by: order_by
                    .as_ref()
                    .map(|specs| {
                        specs
                            .iter()
                            .map(|o| (o.field.as_str(), o.direction.to_ascii_lowercase()))
                            .collect()
                    })
                    .unwrap_or_default(),
            },
        }
    }

    /// Stable identity of this shape.
    pub fn digest(&self) -> String {
        let json = serde_json::to_value(self).unwrap_or(Value::Null);
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"shape1:");
        hasher.update(&canonical_json(&json));
        hasher.finalize().to_hex().to_string()
    }

    /// Every table this shape scans, root first, deduplicated.
    pub fn tables(&self) -> Vec<String> {
        let mut out = Vec::new();
        self.collect_tables(&mut out);
        let mut seen = std::collections::HashSet::new();
        out.retain(|t| seen.insert(t.clone()));
        out
    }

    fn collect_tables(&self, out: &mut Vec<String>) {
        match self {
            Shape::Scan { table } => out.push(table.clone()),
            Shape::Filter { input, .. }
            | Shape::Distinct { input }
            | Shape::Limit { input, .. } => input.collect_tables(out),
            Shape::Join { left, right, .. } | Shape::Union { left, right } => {
                left.collect_tables(out);
                right.collect_tables(out);
            }
            Shape::Project {
                input, subqueries, ..
            } => {
                input.collect_tables(out);
                for (_, (_, sub)) in subqueries {
                    sub.collect_tables(out);
                }
            }
        }
    }

    /// The table the root WHERE applies to: the first scan on the spine.
    pub fn root_table(&self) -> Option<String> {
        self.tables().into_iter().next()
    }

    /// Split off the root WHERE: the single `Filter` sitting directly above the
    /// spine's `Scan`, which is the only place the builder puts a caller
    /// `where`. Subquery filters, joins and anything above are untouched.
    /// Returns the skeleton and the removed predicate (if there was one).
    pub fn split_root_where(&self) -> (Shape, Option<Pred>) {
        let mut taken = None;
        let skeleton = self.strip_root_where(&mut taken);
        (skeleton, taken)
    }

    fn strip_root_where(&self, taken: &mut Option<Pred>) -> Shape {
        match self {
            Shape::Filter { input, predicate } if matches!(**input, Shape::Scan { .. }) => {
                *taken = Some(predicate.clone());
                (**input).clone()
            }
            Shape::Filter { input, predicate } => Shape::Filter {
                input: Box::new(input.strip_root_where(taken)),
                predicate: predicate.clone(),
            },
            Shape::Distinct { input } => Shape::Distinct {
                input: Box::new(input.strip_root_where(taken)),
            },
            Shape::Limit { input, order_by } => Shape::Limit {
                input: Box::new(input.strip_root_where(taken)),
                order_by: order_by.clone(),
            },
            Shape::Project {
                input,
                all,
                fields,
                subqueries,
            } => Shape::Project {
                input: Box::new(input.strip_root_where(taken)),
                all: *all,
                fields: fields.clone(),
                subqueries: subqueries.clone(),
            },
            // A join or union above the scan is not builder output; the spine
            // ends here and whatever WHERE sits below stays part of the shape.
            Shape::Scan { .. } | Shape::Join { .. } | Shape::Union { .. } => self.clone(),
        }
    }
}

/// Bounds on a caller-supplied WHERE. Generous for a UI filter, tight enough
/// that a predicate cannot be used as a CPU sink.
const WHERE_MAX_LEAVES: usize = 64;
const WHERE_MAX_DEPTH: usize = 4;

/// Admit `pred` as the root WHERE of a `whereMode: any` entry only if it is
/// what the query builder can produce: `field op $param` leaves joined by
/// AND/OR, every field a column of `table`.
pub fn validate_builder_where(
    pred: &Pred,
    table: &str,
    columns: Option<&BTreeSet<String>>,
) -> Result<(), String> {
    let Some(columns) = columns else {
        return Err(format!("no column list known for table `{table}`"));
    };
    let mut leaves = 0usize;
    walk_builder_where(pred, table, columns, 0, &mut leaves)
}

fn walk_builder_where(
    pred: &Pred,
    table: &str,
    columns: &BTreeSet<String>,
    depth: usize,
    leaves: &mut usize,
) -> Result<(), String> {
    if depth > WHERE_MAX_DEPTH {
        return Err(format!("WHERE nests deeper than {WHERE_MAX_DEPTH}"));
    }
    match pred {
        Pred::Cmp {
            field,
            rhs: Rhs::Param,
            ..
        } => {
            *leaves += 1;
            if *leaves > WHERE_MAX_LEAVES {
                return Err(format!(
                    "WHERE has more than {WHERE_MAX_LEAVES} comparisons"
                ));
            }
            let root = field.split('.').next().unwrap_or(field);
            if root == "id" || columns.contains(root) {
                Ok(())
            } else {
                Err(format!("`{field}` is not a column of `{table}`"))
            }
        }
        Pred::Cmp {
            field,
            rhs: Rhs::Lit,
            ..
        } => Err(format!(
            "`{field}` is compared against a literal, not a bound $param"
        )),
        Pred::Cmp {
            field,
            rhs: Rhs::Parent(_),
            ..
        } => Err(format!(
            "`{field}` uses a subquery correlation in a root WHERE"
        )),
        Pred::Prefix { field } => Err(format!("prefix match on `{field}` is not builder grammar")),
        Pred::ParamCmp { .. } => Err("a `$param OP value` gate is not builder grammar".into()),
        Pred::True | Pred::False => Err("a constant WHERE is not builder grammar".into()),
        Pred::And { of } | Pred::Or { of } => {
            if of.is_empty() {
                return Err("empty AND/OR".into());
            }
            for p in of {
                walk_builder_where(p, table, columns, depth + 1, leaves)?;
            }
            Ok(())
        }
    }
}

/// Where a compiled entry came from, for `/info`.
#[derive(Clone, Debug, Default, Serialize)]
pub struct Source {
    pub app: String,
    pub version: String,
    pub released_at: String,
    pub entries: usize,
}

/// The allowlist ready for lookups: entries parsed through the converter and
/// indexed by shape digest.
#[derive(Clone, Debug, Default)]
pub struct Compiled {
    static_keys: HashMap<String, usize>,
    any_skeletons: HashMap<String, usize>,
    entries: Vec<Entry>,
    pub sources: Vec<Source>,
    /// `(name, error)` for entries the converter rejected. Surfaced, never
    /// fatal: one bad entry must not take the whole allowlist down.
    pub skipped: Vec<(String, String)>,
}

impl Compiled {
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

/// Parse every entry and index it. `links` must be the circuit's current link
/// map so entries lower exactly like a live registration would; recompile
/// whenever it changes (every Ready transition), not only on a row change.
pub fn compile(entries: Vec<Entry>, sources: Vec<Source>, links: &LinkMap) -> Compiled {
    let mut out = Compiled {
        sources,
        ..Compiled::default()
    };
    for entry in entries {
        let plan = match convert_surql_to_dbsp_with_links(&entry.surql, links)
            .and_then(|v| serde_json::from_value::<OperatorPlan>(v).map_err(anyhow::Error::from))
        {
            Ok(p) => p,
            Err(e) => {
                out.skipped.push((entry.name.clone(), e.to_string()));
                continue;
            }
        };
        let shape = Shape::of(&plan);
        let idx = out.entries.len();
        match entry.where_mode {
            WhereMode::Static => {
                out.static_keys.entry(shape.digest()).or_insert(idx);
            }
            WhereMode::Any => {
                let (skeleton, _) = shape.split_root_where();
                out.any_skeletons.entry(skeleton.digest()).or_insert(idx);
                // A caller may also pass no `where` at all; the bare skeleton
                // is then the full shape and must match as static.
                out.static_keys.entry(skeleton.digest()).or_insert(idx);
            }
        }
        out.entries.push(entry);
    }
    out
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Allowed {
    Static,
    Any,
    Builtin,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Decision {
    Allowed(Allowed),
    Refused { reason: String },
}

/// Shapes the sync core registers on its own behalf (`_00_app_release`,
/// `_00_user_feature`) are always admitted: they scan only synced meta tables,
/// which no app query can reach.
pub fn is_builtin(shape: &Shape) -> bool {
    let tables = shape.tables();
    !tables.is_empty()
        && tables
            .iter()
            .all(|t| ssp_protocol::SYNCED_META_TABLES.contains(&t.as_str()))
}

/// Decide whether `shape` may register. `columns` is the per-table column set
/// (root field names from `INFO FOR TABLE`), consulted only for `any` entries.
pub fn decide(
    compiled: &Compiled,
    shape: &Shape,
    columns: &HashMap<String, BTreeSet<String>>,
) -> Decision {
    if is_builtin(shape) {
        return Decision::Allowed(Allowed::Builtin);
    }
    if compiled.static_keys.contains_key(&shape.digest()) {
        return Decision::Allowed(Allowed::Static);
    }
    let table = shape.root_table().unwrap_or_default();
    let (skeleton, root_where) = shape.split_root_where();
    if let Some(&idx) = compiled.any_skeletons.get(&skeleton.digest()) {
        let entry = &compiled.entries[idx];
        return match root_where {
            None => Decision::Allowed(Allowed::Any),
            Some(pred) => match validate_builder_where(&pred, &table, columns.get(&table)) {
                Ok(()) => Decision::Allowed(Allowed::Any),
                Err(why) => Decision::Refused {
                    reason: format!(
                        "query on `{table}` matches allowlisted shape `{}` but its WHERE is not builder grammar: {why}",
                        entry.name
                    ),
                },
            },
        };
    }
    Decision::Refused {
        reason: format!(
            "shape of query on `{table}` is not in the allowlist ({} entries from {} release{})",
            compiled.entries.len(),
            compiled.sources.len(),
            if compiled.sources.len() == 1 { "" } else { "s" }
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn shape(sql: &str) -> Shape {
        let v = crate::converter::convert_surql_to_dbsp(sql).expect("parse");
        let plan: OperatorPlan = serde_json::from_value(v).expect("plan");
        Shape::of(&plan)
    }

    fn entry(name: &str, surql: &str, where_mode: WhereMode) -> Entry {
        Entry {
            name: name.into(),
            surql: surql.into(),
            where_mode,
            app: "web".into(),
            version: "1.0.0".into(),
        }
    }

    fn cols(table: &str, names: &[&str]) -> HashMap<String, BTreeSet<String>> {
        let mut m = HashMap::new();
        m.insert(
            table.to_string(),
            names.iter().map(|s| s.to_string()).collect(),
        );
        m
    }

    #[test]
    fn limit_and_start_numbers_are_masked() {
        let a = shape("SELECT id, name FROM game WHERE owner = $owner ORDER BY sort_index ASC, id ASC LIMIT 50 START 50");
        let b = shape("SELECT id, name FROM game WHERE owner = $owner ORDER BY sort_index ASC, id ASC LIMIT 1 START 1");
        let c = shape("SELECT id, name FROM game WHERE owner = $owner ORDER BY sort_index ASC, id ASC LIMIT 30");
        assert_eq!(a.digest(), b.digest());
        assert_eq!(a.digest(), c.digest());
    }

    #[test]
    fn missing_limit_is_a_different_shape() {
        let a = shape("SELECT id FROM game WHERE owner = $owner LIMIT 10");
        let b = shape("SELECT id FROM game WHERE owner = $owner");
        assert_ne!(a.digest(), b.digest());
    }

    #[test]
    fn order_by_is_exact() {
        let a = shape("SELECT id FROM game ORDER BY created_at DESC LIMIT 10");
        let b = shape("SELECT id FROM game ORDER BY created_at ASC LIMIT 10");
        let c = shape("SELECT id FROM game ORDER BY id ASC LIMIT 10");
        assert_ne!(a.digest(), b.digest());
        assert_ne!(a.digest(), c.digest());
    }

    #[test]
    fn param_names_are_irrelevant_and_or_branches_collapse() {
        let a = shape("SELECT id FROM game WHERE (white = $white__or0 OR white = $white__or1 OR white = $white__or2)");
        let b = shape("SELECT id FROM game WHERE (white = $white__or0)");
        let c = shape("SELECT id FROM game WHERE (white = $foo OR white = $bar)");
        assert_eq!(a.digest(), b.digest());
        assert_eq!(a.digest(), c.digest());
        let d = shape("SELECT id FROM game WHERE (black = $foo)");
        assert_ne!(a.digest(), d.digest());
    }

    #[test]
    fn operator_is_part_of_the_shape() {
        let a = shape("SELECT id FROM game WHERE created_at > $since");
        let b = shape("SELECT id FROM game WHERE created_at = $since");
        assert_ne!(a.digest(), b.digest());
    }

    #[test]
    fn projection_order_is_irrelevant() {
        let a = shape("SELECT id, username, created_at FROM user LIMIT 24");
        let b = shape("SELECT created_at, id, username FROM user LIMIT 24");
        let c = shape("SELECT id, username FROM user LIMIT 24");
        assert_eq!(a.digest(), b.digest());
        assert_ne!(a.digest(), c.digest());
    }

    #[test]
    fn related_subquery_literal_is_masked_and_order_irrelevant() {
        let a = shape("SELECT id, (SELECT id, username FROM user WHERE id = parent.owner AND role = \"admin\") AS owner, (SELECT id FROM tag WHERE game = parent.id) AS tags FROM game LIMIT 10");
        let b = shape("SELECT id, (SELECT id FROM tag WHERE game = parent.id) AS tags, (SELECT id, username FROM user WHERE id = parent.owner AND role = \"user\") AS owner FROM game LIMIT 10");
        assert_eq!(a.digest(), b.digest());
        let c = shape(
            "SELECT id, (SELECT id FROM user WHERE id = parent.owner) AS owner FROM game LIMIT 10",
        );
        assert_ne!(a.digest(), c.digest());
    }

    #[test]
    fn builtin_meta_tables_always_allowed() {
        let compiled = compile(vec![], vec![], &LinkMap::new());
        let s = shape("SELECT * FROM _00_app_release");
        assert_eq!(
            decide(&compiled, &s, &HashMap::new()),
            Decision::Allowed(Allowed::Builtin)
        );
        let s = shape("SELECT key, variant, payload FROM _00_user_feature");
        assert_eq!(
            decide(&compiled, &s, &HashMap::new()),
            Decision::Allowed(Allowed::Builtin)
        );
        let s = shape("SELECT * FROM _00_query");
        assert!(matches!(
            decide(&compiled, &s, &HashMap::new()),
            Decision::Refused { .. }
        ));
    }

    #[test]
    fn static_entry_matches_the_recorded_shape_only() {
        let compiled = compile(
            vec![entry(
                "qRecentUsers",
                "SELECT id, username, created_at FROM user ORDER BY created_at DESC, id ASC LIMIT 1;",
                WhereMode::Static,
            )],
            vec![],
            &LinkMap::new(),
        );
        let ok = shape(
            "SELECT id, username, created_at FROM user ORDER BY created_at DESC, id ASC LIMIT 24",
        );
        assert_eq!(
            decide(&compiled, &ok, &HashMap::new()),
            Decision::Allowed(Allowed::Static)
        );
        let probe = shape("SELECT id, username, created_at, email FROM user ORDER BY created_at DESC, id ASC LIMIT 24");
        assert!(matches!(
            decide(&compiled, &probe, &HashMap::new()),
            Decision::Refused { .. }
        ));
        let with_where = shape("SELECT id, username, created_at FROM user WHERE email = $e ORDER BY created_at DESC, id ASC LIMIT 24");
        assert!(matches!(
            decide(&compiled, &with_where, &HashMap::new()),
            Decision::Refused { .. }
        ));
    }

    #[test]
    fn any_entry_accepts_builder_grammar_over_columns() {
        let compiled = compile(
            vec![entry(
                "qGamesWindow",
                "SELECT id, white, black FROM game ORDER BY sort_index ASC, id ASC LIMIT 1 START 1;",
                WhereMode::Any,
            )],
            vec![],
            &LinkMap::new(),
        );
        let columns = cols(
            "game",
            &["id", "white", "black", "owner", "sort_index", "date"],
        );
        let ok = shape("SELECT id, white, black FROM game WHERE owner = $owner AND (white = $w0 OR black = $b0) AND date >= $since ORDER BY sort_index ASC, id ASC LIMIT 50 START 100");
        assert_eq!(
            decide(&compiled, &ok, &columns),
            Decision::Allowed(Allowed::Any)
        );
        let no_where =
            shape("SELECT id, white, black FROM game ORDER BY sort_index ASC, id ASC LIMIT 50");
        assert_eq!(
            decide(&compiled, &no_where, &columns),
            Decision::Allowed(Allowed::Static)
        );

        let unknown_col = shape("SELECT id, white, black FROM game WHERE secret = $s ORDER BY sort_index ASC, id ASC LIMIT 50");
        match decide(&compiled, &unknown_col, &columns) {
            Decision::Refused { reason } => assert!(reason.contains("not a column"), "{reason}"),
            other => panic!("expected refusal, got {other:?}"),
        }
        let literal = shape("SELECT id, white, black FROM game WHERE owner = \"user:x\" ORDER BY sort_index ASC, id ASC LIMIT 50");
        assert!(matches!(
            decide(&compiled, &literal, &columns),
            Decision::Refused { .. }
        ));
        let other_projection = shape(
            "SELECT id, pgn FROM game WHERE owner = $o ORDER BY sort_index ASC, id ASC LIMIT 50",
        );
        assert!(matches!(
            decide(&compiled, &other_projection, &columns),
            Decision::Refused { .. }
        ));
        let no_columns_known = decide(&compiled, &ok, &HashMap::new());
        assert!(matches!(no_columns_known, Decision::Refused { .. }));
    }

    #[test]
    fn any_entry_depth_cap() {
        let mut pred = Pred::Cmp {
            field: "id".into(),
            op: Op::Eq,
            rhs: Rhs::Param,
        };
        for _ in 0..(WHERE_MAX_DEPTH + 1) {
            pred = Pred::And {
                of: [pred].into_iter().collect(),
            };
        }
        let columns: BTreeSet<String> = ["id".to_string()].into_iter().collect();
        assert!(validate_builder_where(&pred, "game", Some(&columns)).is_err());
    }

    #[test]
    fn bad_entries_are_skipped_not_fatal() {
        let compiled = compile(
            vec![
                entry("broken", "SELEC nope", WhereMode::Static),
                entry("ok", "SELECT id FROM user LIMIT 1", WhereMode::Static),
            ],
            vec![],
            &LinkMap::new(),
        );
        assert_eq!(compiled.len(), 1);
        assert_eq!(compiled.skipped.len(), 1);
        assert_eq!(compiled.skipped[0].0, "broken");
    }

    #[test]
    fn mode_parses() {
        assert_eq!("warn".parse::<Mode>().unwrap(), Mode::Warn);
        assert_eq!("ENFORCE".parse::<Mode>().unwrap(), Mode::Enforce);
        assert_eq!("".parse::<Mode>().unwrap(), Mode::Off);
        assert!("maybe".parse::<Mode>().is_err());
    }
}

#[cfg(test)]
mod json_fixture {
    //! `SPKY_ALLOWLIST_JSON=/path/to/query.ts.allowlist.json cargo test -p ssp
    //! allowlist_json_compiles -- --ignored --nocapture` compiles a generator
    //! output through the converter and fails on any entry it cannot parse.
    //! The generator emits raw surql, so this is the one place a builder
    //! construct the SSP grammar does not cover shows up before a deploy.
    use super::*;

    #[test]
    #[ignore]
    fn allowlist_json_compiles() {
        let Ok(path) = std::env::var("SPKY_ALLOWLIST_JSON") else {
            eprintln!("SPKY_ALLOWLIST_JSON not set");
            return;
        };
        let raw = std::fs::read_to_string(&path).expect("read json");
        let doc: Value = serde_json::from_str(&raw).expect("parse json");
        let entries: Vec<Entry> =
            serde_json::from_value(doc["entries"].clone()).expect("entries[]");
        let total = entries.len();
        let compiled = compile(entries, vec![], &LinkMap::new());
        for (name, err) in &compiled.skipped {
            eprintln!("SKIPPED {name}: {err}");
        }
        eprintln!("{} of {total} entries compiled", compiled.len());
        assert!(
            compiled.skipped.is_empty(),
            "{} entries did not parse",
            compiled.skipped.len()
        );
    }
}
